---
version: '3'
services:

  consul:
    image: consul:latest
    ports:
      - "8501:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - SERVICE_IGNORE=true

  consul-registrator:
    image: gliderlabs/registrator:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: ["consul://consul:8500"]
    depends_on:
      - consul

  connect-router:
    image: nicholasjackson/consul-connect-router:latest
    ports:
      - "8181:8181"
    command: [
      '--upstream=service=emojify-website#path=/',
      '--upstream=service=emojify-api#path=/api',
      '--upstream=service=emojify-auth#path=/auth',
      '--consul_addr=http://consul:8500'
    ]
    depends_on:
      - consul
    environment:
      - SERVICE_NAME=connect-router

  emojify-website:
    image: nicholasjackson/emojify-website:dev
    ports:
      - "3006:3006"
    environment:
      - SERVICE_NAME=emojify-website
      - SERVICE_3006_CHECK_HTTP=/
      - SERVICE_3006_CHECK_INTERVAL=15s
      - SERVICE_3006_CHECK_TIMEOUTL=1s
    volumes:
      - .:/frontend

  emojify-website-proxy:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-website"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-website',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-website:8443',
      '-service-addr', 'localhost:3006',
      '-register'
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul

  emojify-auth:
    image: keratin/authn-server:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=sqlite3://:memory:?mode=memory\&cache=shared
      - AUTHN_URL=http://localhost:3000
      - APP_DOMAINS=ngrok.local.demo.gs
      - SECRET_KEY_BASE=changeme
      - SERVICE_NAME=emojify-auth
      - SERVICE_3000_CHECK_HTTP=/health
      - SERVICE_3000_CHECK_INTERVAL=15s
      - SERVICE_3000_CHECK_TIMEOUTL=1s
      - GITHUB_OAUTH_CREDENTIALS=${GITHUB_AUTH_CLIENT_ID}:${GITHUB_AUTH_CLIENT_SECRET}
      - PROXIED=true
    entrypoint: "sh"
    command: ["-c", "./authn migrate && ./authn server"]

  emojify-auth-proxy:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-auth"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-auth',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-auth:8443',
      '-service-addr', 'localhost:3000',
      '-register'
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul

  emojify-api:
    image: "nicholasjackson/emojify-api:latest"
    ports:
      - "9090:9090"
    entrypoint: "/service/emojify-api"
    command: [
      "-allow-origin=*",
      "-authn-server=http://localhost:3000",
      "-authn-audience=localhost"
    ]
    environment:
      - FACEBOX=http://localhost:8080
      - SERVICE_NAME=emojify-api
      - SERVICE_9090_CHECK_HTTP=/health
      - SERVICE_9090_CHECK_INTERVAL=15s
      - SERVICE_9090_CHECK_TIMEOUTL=1s

  emojify-api-proxy:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-api"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-api',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-api:8443',
      '-service-addr', 'emojify-api:9090',
      '-register',
      '-upstream', 'emojify-facebox:8080',
      '-upstream', 'emojify-auth:3000'
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul

  emojify-facebox:
    image: "machinebox/facebox"
    ports:
      - "8080:8080"
    environment:
      - MB_KEY=${MB_KEY}
      - SERVICE_NAME=emojify-facebox
      - SERVICE_8080_CHECK_HTTP=/healthz
      - SERVICE_8080_CHECK_INTERVAL=15s
      - SERVICE_8080_CHECK_TIMEOUTL=1s

  emojify-facebox-proxy:
    image: consul:latest
    entrypoint: "consul"
    network_mode: "service:emojify-facebox"
    command: [
      'connect',
      'proxy',
      '-log-level=DEBUG',
      '-service', 'emojify-facebox',
      '-http-addr', 'consul:8500',
      '-listen', 'emojify-facebox:8443',
      '-service-addr', 'localhost:8080',
      '-register',
    ]
    environment:
      - SERVICE_IGNORE=true
    depends_on:
      - consul
